### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by rakantoh** [DcmanProductions/VillagerLeads#2]
This is the most java version support of a villager leashable mod type, supporting from 1.15.x to 1.20.6, so please, update to be compatible with 1.21.x, and fix a little issue that consist in if the player leash a villager in a fence and accidentally clic with a lead in hand, the villager take the new lead from the player and the lead in the fence dissapears, causing sometimes losing leads.
Thanks.

**Comment by Drew-Chase** [comment]
Updated!
https://modrinth.com/mod/villager-leads/version/0.0.3
